spring:
  application:
    name: auth-service

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

codeatlas:
  auth:
    pending-registration:
      ttl: 10m